// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RinconDL.Contexts;

namespace RinconAPI.Migrations
{
    [DbContext(typeof(RinconContext))]
    partial class RinconContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("RinconDL.Entities.Carrito", b =>
                {
                    b.Property<int>("CarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioFId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarritoId");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("RinconDL.Entities.Carta", b =>
                {
                    b.Property<int>("CartaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartaName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Img")
                        .HasColumnType("TEXT");

                    b.Property<int>("JuegoFId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartaId");

                    b.ToTable("Cartas");

                    b.HasData(
                        new
                        {
                            CartaId = 1,
                            CartaName = "Dunsparce (NDI 54)",
                            Img = "https://static.cardmarket.com/img/a2874630bf08babe923e75b1a73fba29/items/51/NDI/274565.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 2,
                            CartaName = "Imakuni?'s Doduo (EVO 112)",
                            Img = "https://static.cardmarket.com/img/60b895275f86d14cc1fe1090647467de/items/51/EVO/293474.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 3,
                            CartaName = "Elite Trainer Box de Destinos Brillantes",
                            Img = "https://static.cardmarket.com/img/f80b7d3d6526c6b03022cf4d1606b0db/items/1016/526120.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 4,
                            CartaName = "Umbreon ☆ (POP5 17)",
                            Img = "https://static.cardmarket.com/img/76f23de2b6ac2248fd638ab9ec1709a5/items/51/POP5/277499.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 5,
                            CartaName = "Karen's Umbreon (VS 091)",
                            Img = "https://static.cardmarket.com/img/dd328e0e93d36ca6fd641be69861a678/items/51/VS/554561.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 6,
                            CartaName = "Umbreon & Darkrai GX (SM SM241)",
                            Img = "https://static.cardmarket.com/img/e01733c9dd53bb665cd2b1d1a91da8f3/items/51/SM/449108.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 7,
                            CartaName = "Umbreon GX (HIF SV69)",
                            Img = "https://static.cardmarket.com/img/55a3d0ee23b66fcaa2f6d85b17c4a485/items/51/HIF/396982.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 8,
                            CartaName = "Dunsparce (LM 31)",
                            Img = "https://static.cardmarket.com/img/f1587e504ae57a0aaec8d5568a59b02f/items/51/LM/276908.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 9,
                            CartaName = "MSlowbro EX (EVO 27)",
                            Img = "https://static.cardmarket.com/img/60b895275f86d14cc1fe1090647467de/items/51/EVO/293384.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 10,
                            CartaName = "Kyogre (SHF 21)",
                            Img = "https://static.cardmarket.com/img/dc2eff771158e8a3290a28a19a4b673a/items/51/SHF/539128.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 11,
                            CartaName = "Caja de sobres de Reinado Escalofriante (36 Boosters)",
                            Img = "https://static.cardmarket.com/img/3d609c303872afb782eb7507cdceb045/items/53/557968.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 12,
                            CartaName = "Unown Z (NDE 60)",
                            Img = "https://static.cardmarket.com/img/246942528d34579e35a1640add2a0106/items/51/NDE/274712.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 13,
                            CartaName = "Muk & Alolan Muk GX (UNB 197)",
                            Img = "https://static.cardmarket.com/img/d0b7103cb66fdd8d9a79448505f2a8ba/items/51/UNB/372479.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 14,
                            CartaName = "Nessa (VIV 183)",
                            Img = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512625.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 15,
                            CartaName = "Roxy (SSH 200)",
                            Img = "https://static.cardmarket.com/img/159c59e8c594e2f0ce00ce3186029227/items/51/SSH/437094.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 16,
                            CartaName = "Alana (Rara Ultra) (ROS 108)",
                            Img = "https://static.cardmarket.com/img/5112dc4d56bb3a367bf77e94b03f47e9/items/51/ROS/282776.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 17,
                            CartaName = "Sentimientos de Cintia (LA 131)",
                            Img = "https://static.cardmarket.com/img/bb28a68f0f7905aa6719f8fccde4f5ae/items/51/LA/278280.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 18,
                            CartaName = "Jere's Arceus & Dialga & Palkia GX (CEC 221)",
                            Img = "https://static.cardmarket.com/img/d3a1c2a0bbd77a12645671b7e6d94845/items/51/CEC/408699.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 19,
                            CartaName = "Zacian V (SSH 211)",
                            Img = "https://static.cardmarket.com/img/159c59e8c594e2f0ce00ce3186029227/items/51/SSH/437144.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 20,
                            CartaName = "Energía Oscura (NG 104)",
                            Img = "https://static.cardmarket.com/img/9f4db66a8b0ceb539c3abe986b974556/items/51/NG/274504.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 21,
                            CartaName = "Sandra's Lickilicky (UNB 153)",
                            Img = "https://static.cardmarket.com/img/d0b7103cb66fdd8d9a79448505f2a8ba/items/51/UNB/372441.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 22,
                            CartaName = "N's Resolve (CEC 232)",
                            Img = "https://static.cardmarket.com/img/d3a1c2a0bbd77a12645671b7e6d94845/items/51/CEC/408754.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 23,
                            CartaName = "Jirachi (VIV 119)",
                            Img = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            JuegoFId = 1
                        },
                        new
                        {
                            CartaId = 24,
                            CartaName = "Duza the Meteor Cubic Vessel (V.1 - Gold Secret Rare)",
                            Img = "",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 25,
                            CartaName = "Yata-Garasu",
                            Img = "https://static.cardmarket.com/img/0640f3af34af39ceebe795136f6b9926/items/5/LOD/106466.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 26,
                            CartaName = "Kuriboh",
                            Img = "https://static.cardmarket.com/img/1676935576eb745ea623d2d0f45e172f/items/5/MRD/104170.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 27,
                            CartaName = "Dragoncella Cocinera",
                            Img = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413824.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 28,
                            CartaName = "Dragoncella Enfermera",
                            Img = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413804.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 29,
                            CartaName = "Dragoncella Criada",
                            Img = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413834.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 30,
                            CartaName = "Coloso Dragón de Trueno",
                            Img = "https://static.cardmarket.com/img/603f46720c8c9058776ce35b8b80a593/items/5/OP10/372531.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 31,
                            CartaName = "Dragoncella Amadellaves",
                            Img = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413844.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 32,
                            CartaName = "Fusión del Dragón de Trueno",
                            Img = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364864.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 33,
                            CartaName = "Halcondragón de Trueno",
                            Img = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364824.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 34,
                            CartaName = "Oscurodragón de Trueno",
                            Img = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364823.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 35,
                            CartaName = "Rugidodragón de Trueno",
                            Img = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364825.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 36,
                            CartaName = "Mekk-Caballero Cielo Azul",
                            Img = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/314705.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 37,
                            CartaName = "Mekk-Caballero Cruzadia Avramax",
                            Img = "https://static.cardmarket.com/img/5898c8c88ee0c23222266865532e7182/items/5/DANE/372860.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 38,
                            CartaName = "Mekk-Caballero Ocaso Púrpura",
                            Img = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/315857.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 39,
                            CartaName = "Mekk-Caballero Avram",
                            Img = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/316253.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 40,
                            CartaName = "Reencarnación Bromiestrella",
                            Img = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299037.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 41,
                            CartaName = "Bromiestrella Trompeta",
                            Img = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299025.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 42,
                            CartaName = "Bromiestrella Lycoris",
                            Img = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299024.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 43,
                            CartaName = "Diveragua Brominiños",
                            Img = "https://static.cardmarket.com/img/a9ac78ac1dbd553e0bff259d886f2ed0/items/5/HISU/366620.jpg",
                            JuegoFId = 2
                        },
                        new
                        {
                            CartaId = 44,
                            CartaName = "Cazadora de Krufix",
                            Img = "https://static.cardmarket.com/img/90be405454bca7f37d6eabfb37dddb11/items/1/BNG/265891.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 45,
                            CartaName = "Astucia de Kaya",
                            Img = "https://static.cardmarket.com/img/4ecddc6780ce572d24df7929b2720465/items/1/MH1/375117.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 46,
                            CartaName = "Manamorfosis",
                            Img = "https://static.cardmarket.com/img/bdfbfd4952ea5d41128451495b6e6fd1/items/1/SHM/19225.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 47,
                            CartaName = "Devastador arcoligado",
                            Img = "https://static.cardmarket.com/img/1b726e5efe946b94db7527e1c6d1606c/items/1/DCI/373108.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 48,
                            CartaName = "Brezal azotado por el viento",
                            Img = "https://static.cardmarket.com/img/c21340a8e384bef0513bfcc9dbdf37e5/items/1/KTK/269125.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 49,
                            CartaName = "Demonio cacofónico",
                            Img = "https://static.cardmarket.com/img/2560ea479b26fb247a05c378f76f577b/items/1/CMA/298002.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 50,
                            CartaName = "Segunda recolección",
                            Img = "https://static.cardmarket.com/img/a85b647e85992648d1ca190b4ba671d0/items/1/C19/392327.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 51,
                            CartaName = "Diezmo de maná",
                            Img = "https://static.cardmarket.com/img/5d7a85496b818d6ed2017183875bca6f/items/1/MPR/19010.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 52,
                            CartaName = "Verdant Command",
                            Img = "https://static.cardmarket.com/img/b4c041672c7d6df4038e6bb7bb290f8c/items/1/MH2/566441.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 53,
                            CartaName = "Espadas en guadañas (V.1)",
                            Img = "https://static.cardmarket.com/img/6ae66ec70d8ede75e8dab6c90f75eb26/items/1/STA/540521.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 54,
                            CartaName = "Optar (V.2)",
                            Img = "https://static.cardmarket.com/img/6ae66ec70d8ede75e8dab6c90f75eb26/items/1/STA/540551.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 55,
                            CartaName = "Jace Beleren",
                            Img = "https://static.cardmarket.com/img/e3fc2e863bf0f29ce91126edbf3e064c/items/1/SS1/320582.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 56,
                            CartaName = "Pasos aplastadores",
                            Img = "https://static.cardmarket.com/img/5a0199344cad68eebeefca6fa24e52c3/items/1/MH1/375120.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 57,
                            CartaName = "Bola de fuego",
                            Img = "https://static.cardmarket.com/img/5d7a85496b818d6ed2017183875bca6f/items/1/MPR/17570.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 58,
                            CartaName = "Sudden Edict",
                            Img = "https://static.cardmarket.com/img/8ace9ad5f0a1d72d20a9f77be2cf5199/items/1/MH2/566661.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 59,
                            CartaName = "Búmerang",
                            Img = "https://static.cardmarket.com/img/140882aae7d629478ae109485bd0c387/items/1/GW/17559.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 60,
                            CartaName = "Zur el Encantador",
                            Img = "https://static.cardmarket.com/img/c98ae71d8806dd919d3957532efa5083/items/1/XCMR/510720.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 61,
                            CartaName = "Devolver el favor",
                            Img = "https://static.cardmarket.com/img/1fedf8ffa935b0c57e9e72b98d244421/items/1/ROE/22567.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 62,
                            CartaName = "Protectora de esencia",
                            Img = "https://static.cardmarket.com/img/62d92924aaef812ff996b5d3e725841c/items/1/PLC/14324.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 63,
                            CartaName = "Black Lotus",
                            Img = "https://static.cardmarket.com/img/82721fdcc32d450e26c2e52900e58f17/items/1/LEA/5465.jpg",
                            JuegoFId = 3
                        },
                        new
                        {
                            CartaId = 64,
                            CartaName = "King Vegeta, Umbral Invader",
                            Img = "https://static.cardmarket.com/img/da48a0b1a709e19aabfe340c207f51df/items/1049/BT13/557521.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 65,
                            CartaName = "Royal Supremacy",
                            Img = "https://static.cardmarket.com/img/d90bd04a2e5f72717e8c7bd86ffae51b/items/1049/BT13/557546.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 66,
                            CartaName = "Golden Frieza, Pinnacle of the Clan",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/550021.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 67,
                            CartaName = "Frieza, Revived and Reviled",
                            Img = "https://static.cardmarket.com/img/a64b38b5ad3f59b8f1b2c55b2116eab4/items/1049/BT13/557533.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 68,
                            CartaName = "The Power of a Super Saiyan",
                            Img = "https://static.cardmarket.com/img/e8a55cc61ee2cc9246eb0021085db33e/items/1049/BT13/557572.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 69,
                            CartaName = "Majin Buu, Assault of the Agents of Destruction",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549866.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 70,
                            CartaName = "Bardock, Pride of a Low-Class Warrior",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549721.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 71,
                            CartaName = "Demon God Towa, Ritual at Hand",
                            Img = "https://static.cardmarket.com/img/1591f47c3f3b0a081912dd7a90e470d4/items/1049/BT13/557586.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 72,
                            CartaName = "Chilled, Let the Battle Begin",
                            Img = "https://static.cardmarket.com/img/602cb1dd0d7d3ea4b08fb1f75d61b7e3/items/1049/BT13/557522.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 73,
                            CartaName = "SS Bardock, Super Saiyan Enlightenment",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549746.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 74,
                            CartaName = "SS2 Son Gohan, Astonishing Strike",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549876.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 75,
                            CartaName = "SSB Vegeta, at Full Power",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549801.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 76,
                            CartaName = "SS Son Goku, the Legend Personified",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549756.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 77,
                            CartaName = "Darkness Judgment",
                            Img = "https://static.cardmarket.com/img/049c1544d12a5ed4efc5755a9cbfd855/items/1049/BT13/557599.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 78,
                            CartaName = "SSB Son Goku, at Full Power",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549781.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 79,
                            CartaName = "Mechikabura, Ritual at Hand",
                            Img = "https://static.cardmarket.com/img/304f666ad0dba00c97635d4f7ad60a35/items/1049/BT13/557591.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 80,
                            CartaName = "Boujack, on a Rampage",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549926.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 81,
                            CartaName = "King Vegeta's Imposing Presence",
                            Img = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549846.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 82,
                            CartaName = "Majin Buu, Assault of the Agents of Destruction (V.2 - Special Rare)",
                            Img = "https://static.cardmarket.com/img/23a714196691e1097092b657e2fcf815/items/1049/BT13/565913.jpg",
                            JuegoFId = 4
                        },
                        new
                        {
                            CartaId = 83,
                            CartaName = "SS4 Vegeta, Thwarting the Dark Empire",
                            Img = "https://static.cardmarket.com/img/01ffd411b94cbdef5aab781cdc7d35b3/items/1049/BT13/557579.jpg",
                            JuegoFId = 4
                        });
                });

            modelBuilder.Entity("RinconDL.Entities.CartaCarrito", b =>
                {
                    b.Property<int>("CartaCarritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarritoFId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartaVendedorFId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FCantidad")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartaCarritoId");

                    b.ToTable("CartasCarrito");
                });

            modelBuilder.Entity("RinconDL.Entities.CartaVendedor", b =>
                {
                    b.Property<int>("CartaVendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartaFId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CartaFName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("FImg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("VendedorFId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartaVendedorId");

                    b.ToTable("CartasVendedor");

                    b.HasData(
                        new
                        {
                            CartaVendedorId = 1,
                            Cantidad = 10,
                            CartaFId = 1,
                            CartaFName = "Dunsparce (NDI 54)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/a2874630bf08babe923e75b1a73fba29/items/51/NDI/274565.jpg",
                            Idioma = "es",
                            Precio = 250.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 2,
                            Cantidad = 20,
                            CartaFId = 19,
                            CartaFName = "Zacian V (SSH 211)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/159c59e8c594e2f0ce00ce3186029227/items/51/SSH/437144.jpg",
                            Idioma = "en",
                            Precio = 50.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 3,
                            Cantidad = 30,
                            CartaFId = 12,
                            CartaFName = "Unown Z (NDE 60)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/246942528d34579e35a1640add2a0106/items/51/NDE/274712.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 4,
                            Cantidad = 40,
                            CartaFId = 20,
                            CartaFName = "Energía Oscura (NG 104)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/9f4db66a8b0ceb539c3abe986b974556/items/51/NG/274504.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 25,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 5,
                            Cantidad = 10,
                            CartaFId = 2,
                            CartaFName = "Imakuni?'s Doduo (EVO 112)",
                            Estado = "Casi Perfecta",
                            FImg = "https://static.cardmarket.com/img/60b895275f86d14cc1fe1090647467de/items/51/EVO/293474.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 6,
                            Cantidad = 20,
                            CartaFId = 10,
                            CartaFName = "Kyogre (SHF 21)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/dc2eff771158e8a3290a28a19a4b673a/items/51/SHF/539128.jpg",
                            Idioma = "en",
                            Precio = 50.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 7,
                            Cantidad = 30,
                            CartaFId = 20,
                            CartaFName = "Energía Oscura (NG 104)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/9f4db66a8b0ceb539c3abe986b974556/items/51/NG/274504.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 8,
                            Cantidad = 40,
                            CartaFId = 9,
                            CartaFName = "MSlowbro EX (EVO 27)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/60b895275f86d14cc1fe1090647467de/items/51/EVO/293384.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 26,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 9,
                            Cantidad = 10,
                            CartaFId = 1,
                            CartaFName = "Dunsparce (NDI 54)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/a2874630bf08babe923e75b1a73fba29/items/51/NDI/274565.jpg",
                            Idioma = "en",
                            Precio = 25.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 10,
                            Cantidad = 20,
                            CartaFId = 4,
                            CartaFName = "Umbreon ☆ (POP5 17)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/76f23de2b6ac2248fd638ab9ec1709a5/items/51/POP5/277499.jpg",
                            Idioma = "en",
                            Precio = 50.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 11,
                            Cantidad = 30,
                            CartaFId = 6,
                            CartaFName = "Umbreon & Darkrai GX (SM SM241)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/e01733c9dd53bb665cd2b1d1a91da8f3/items/51/SM/449108.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 12,
                            Cantidad = 40,
                            CartaFId = 16,
                            CartaFName = "Alana (Rara Ultra) (ROS 108)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/5112dc4d56bb3a367bf77e94b03f47e9/items/51/ROS/282776.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 27,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 13,
                            Cantidad = 10,
                            CartaFId = 21,
                            CartaFName = "Sen's Lickilicky (UNB 153)",
                            Estado = "Malo",
                            FImg = "https://static.cardmarket.com/img/d0b7103cb66fdd8d9a79448505f2a8ba/items/51/UNB/372441.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 14,
                            Cantidad = 20,
                            CartaFId = 3,
                            CartaFName = "Elite Trainer Box de Destinos Brillantes",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/f80b7d3d6526c6b03022cf4d1606b0db/items/1016/526120.jpg",
                            Idioma = "en",
                            Precio = 50.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 15,
                            Cantidad = 30,
                            CartaFId = 12,
                            CartaFName = "Unown Z (NDE 60)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/246942528d34579e35a1640add2a0106/items/51/NDE/274712.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 16,
                            Cantidad = 40,
                            CartaFId = 22,
                            CartaFName = "N's Resolve (CEC 232)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/d3a1c2a0bbd77a12645671b7e6d94845/items/51/CEC/408754.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 28,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 17,
                            Cantidad = 10,
                            CartaFId = 8,
                            CartaFName = "Dunsparce (LM 31)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/f1587e504ae57a0aaec8d5568a59b02f/items/51/LM/276908.jpg",
                            Idioma = "en",
                            Precio = 25.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 18,
                            Cantidad = 30,
                            CartaFId = 18,
                            CartaFName = "Jere's Arceus & Dialga & Palkia GX (CEC 221)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/d3a1c2a0bbd77a12645671b7e6d94845/items/51/CEC/408699.jpg",
                            Idioma = "en",
                            Precio = 5.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 19,
                            Cantidad = 30,
                            CartaFId = 4,
                            CartaFName = "Umbreon ☆ (POP5 17",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/76f23de2b6ac2248fd638ab9ec1709a5/items/51/POP5/277499.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 20,
                            Cantidad = 40,
                            CartaFId = 19,
                            CartaFName = "Zacian V (SSH 211)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/159c59e8c594e2f0ce00ce3186029227/items/51/SSH/437144.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 29,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 21,
                            Cantidad = 10,
                            CartaFId = 14,
                            CartaFName = "Nessa (VIV 183)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512625.jpg",
                            Idioma = "en",
                            Precio = 25.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 22,
                            Cantidad = 20,
                            CartaFId = 15,
                            CartaFName = "Roxy (SSH 200)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/159c59e8c594e2f0ce00ce3186029227/items/51/SSH/437094.jpg",
                            Idioma = "en",
                            Precio = 50.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 23,
                            Cantidad = 30,
                            CartaFId = 13,
                            CartaFName = "Muk & Alolan Muk GX (UNB 197)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/d0b7103cb66fdd8d9a79448505f2a8ba/items/51/UNB/372479.jpg",
                            Idioma = "en",
                            Precio = 75.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 24,
                            Cantidad = 40,
                            CartaFId = 17,
                            CartaFName = "Sentimientos de Cintia (LA 131)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/bb28a68f0f7905aa6719f8fccde4f5ae/items/51/LA/278280.jpg",
                            Idioma = "en",
                            Precio = 100.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 30,
                            Cantidad = 1,
                            CartaFId = 23,
                            CartaFName = "Jirachi (VIV 119)",
                            Estado = "Excelente",
                            FImg = "https://static.cardmarket.com/img/4b90c545640b29a90f983e574decb2d9/items/51/VIV/512305.jpg",
                            Idioma = "en",
                            Precio = 1000.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 31,
                            Cantidad = 10,
                            CartaFId = 26,
                            CartaFName = "Kuriboh",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/1676935576eb745ea623d2d0f45e172f/items/5/MRD/104170.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 32,
                            Cantidad = 20,
                            CartaFId = 40,
                            CartaFName = "Reencarnación Bromiestrella",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299037.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 33,
                            Cantidad = 30,
                            CartaFId = 43,
                            CartaFName = "Diveragua Brominiños",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/a9ac78ac1dbd553e0bff259d886f2ed0/items/5/HISU/366620.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 34,
                            Cantidad = 40,
                            CartaFId = 25,
                            CartaFName = "Yata-Garasu",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/0640f3af34af39ceebe795136f6b9926/items/5/LOD/106466.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 35,
                            Cantidad = 10,
                            CartaFId = 40,
                            CartaFName = "Reencarnación Bromiestrella",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299037.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 36,
                            Cantidad = 20,
                            CartaFId = 41,
                            CartaFName = "Bromiestrella Trompeta",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299025.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 37,
                            Cantidad = 30,
                            CartaFId = 42,
                            CartaFName = "Bromiestrella Lycoris",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/69514be8f52437e3c33838f34d4a450e/items/5/COTD/299024.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 38,
                            Cantidad = 40,
                            CartaFId = 25,
                            CartaFName = "Yata-Garasu",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/0640f3af34af39ceebe795136f6b9926/items/5/LOD/106466.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 39,
                            Cantidad = 10,
                            CartaFId = 24,
                            CartaFName = "Duza the Meteor Cubic Vessel (V.1 - Gold Secret Rare)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/ab9c65d1defa6b5d3f070f78d2a12605/items/5/MVP1/294993.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 40,
                            Cantidad = 20,
                            CartaFId = 27,
                            CartaFName = "Dragoncella Cocinera",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413824.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 41,
                            Cantidad = 30,
                            CartaFId = 30,
                            CartaFName = "Coloso Dragón de Trueno",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/603f46720c8c9058776ce35b8b80a593/items/5/OP10/372531.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 42,
                            Cantidad = 40,
                            CartaFId = 25,
                            CartaFName = "Yata-Garasu",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/0640f3af34af39ceebe795136f6b9926/items/5/LOD/106466.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 43,
                            Cantidad = 10,
                            CartaFId = 36,
                            CartaFName = "Mekk-Caballero Cielo Azul",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/314705.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 44,
                            Cantidad = 20,
                            CartaFId = 37,
                            CartaFName = "Mekk-Caballero Cruzadia Avramax",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/5898c8c88ee0c23222266865532e7182/items/5/DANE/372860.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 45,
                            Cantidad = 30,
                            CartaFId = 38,
                            CartaFName = "Mekk-Caballero Ocaso Púrpura",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/315857.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 46,
                            Cantidad = 40,
                            CartaFId = 39,
                            CartaFName = "Mekk-Caballero Avram",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/551811584f52ae96c4bd944cb46ee6c1/items/5/EXFO/316253.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 47,
                            Cantidad = 10,
                            CartaFId = 32,
                            CartaFName = "Fusión del Dragón de Trueno",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364864.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 48,
                            Cantidad = 20,
                            CartaFId = 33,
                            CartaFName = "Halcondragón de Trueno",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364824.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 49,
                            Cantidad = 30,
                            CartaFId = 34,
                            CartaFName = "Oscurodragón de Trueno",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364823.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 50,
                            Cantidad = 40,
                            CartaFId = 35,
                            CartaFName = "Rugidodragón de Trueno",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c364cc93cb1f300502a959073f6dd38e/items/5/SOFU/364825.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 51,
                            Cantidad = 10,
                            CartaFId = 27,
                            CartaFName = "Dragoncella Cocinera",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413824.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 52,
                            Cantidad = 20,
                            CartaFId = 28,
                            CartaFName = "Dragoncella Enfermera",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413804.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 53,
                            Cantidad = 30,
                            CartaFId = 29,
                            CartaFName = "Dragoncella Criada",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413834.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 54,
                            Cantidad = 40,
                            CartaFId = 31,
                            CartaFName = "Dragoncella Amadellaves",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/3da085f7567ff02861ad1e045b5fe11b/items/5/MYFI/413844.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 55,
                            Cantidad = 10,
                            CartaFId = 44,
                            CartaFName = "Cazadora de Krufix",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/90be405454bca7f37d6eabfb37dddb11/items/1/BNG/265891.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 56,
                            Cantidad = 20,
                            CartaFId = 45,
                            CartaFName = "Astucia de Kaya",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/4ecddc6780ce572d24df7929b2720465/items/1/MH1/375117.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 57,
                            Cantidad = 30,
                            CartaFId = 46,
                            CartaFName = "Manamorfosis",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/bdfbfd4952ea5d41128451495b6e6fd1/items/1/SHM/19225.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 58,
                            Cantidad = 40,
                            CartaFId = 59,
                            CartaFName = "Búmerang",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/140882aae7d629478ae109485bd0c387/items/1/GW/17559.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 59,
                            Cantidad = 10,
                            CartaFId = 47,
                            CartaFName = "Devastador arcoligado",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/1b726e5efe946b94db7527e1c6d1606c/items/1/DCI/373108.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 60,
                            Cantidad = 20,
                            CartaFId = 48,
                            CartaFName = "Brezal azotado por el viento",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c21340a8e384bef0513bfcc9dbdf37e5/items/1/KTK/269125.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 61,
                            Cantidad = 30,
                            CartaFId = 49,
                            CartaFName = "Demonio cacofónico",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/2560ea479b26fb247a05c378f76f577b/items/1/CMA/298002.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 62,
                            Cantidad = 40,
                            CartaFId = 63,
                            CartaFName = "Black Lotus",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/82721fdcc32d450e26c2e52900e58f17/items/1/LEA/5465.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 63,
                            Cantidad = 10,
                            CartaFId = 50,
                            CartaFName = "Segunda recolección",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/a85b647e85992648d1ca190b4ba671d0/items/1/C19/392327.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 64,
                            Cantidad = 20,
                            CartaFId = 51,
                            CartaFName = "Diezmo de maná",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/5d7a85496b818d6ed2017183875bca6f/items/1/MPR/19010.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 65,
                            Cantidad = 30,
                            CartaFId = 52,
                            CartaFName = "Verdant Command",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b4c041672c7d6df4038e6bb7bb290f8c/items/1/MH2/566441.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 66,
                            Cantidad = 40,
                            CartaFId = 63,
                            CartaFName = "Black Lotus",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/82721fdcc32d450e26c2e52900e58f17/items/1/LEA/5465.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 67,
                            Cantidad = 10,
                            CartaFId = 53,
                            CartaFName = "Espadas en guadañas (V.1)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/6ae66ec70d8ede75e8dab6c90f75eb26/items/1/STA/540521.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 68,
                            Cantidad = 20,
                            CartaFId = 54,
                            CartaFName = "Optar (V.2)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/6ae66ec70d8ede75e8dab6c90f75eb26/items/1/STA/540551.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 69,
                            Cantidad = 30,
                            CartaFId = 55,
                            CartaFName = "Jace Beleren",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/e3fc2e863bf0f29ce91126edbf3e064c/items/1/SS1/320582.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 70,
                            Cantidad = 40,
                            CartaFId = 59,
                            CartaFName = "Búmerang",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/140882aae7d629478ae109485bd0c387/items/1/GW/17559.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 71,
                            Cantidad = 10,
                            CartaFId = 56,
                            CartaFName = "Pasos aplastadores",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/5a0199344cad68eebeefca6fa24e52c3/items/1/MH1/375120.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 72,
                            Cantidad = 20,
                            CartaFId = 57,
                            CartaFName = "Bola de fuego",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/5d7a85496b818d6ed2017183875bca6f/items/1/MPR/17570.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 73,
                            Cantidad = 30,
                            CartaFId = 58,
                            CartaFName = "Sudden Edict",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/8ace9ad5f0a1d72d20a9f77be2cf5199/items/1/MH2/566661.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 74,
                            Cantidad = 40,
                            CartaFId = 59,
                            CartaFName = "Búmerang",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/140882aae7d629478ae109485bd0c387/items/1/GW/17559.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 75,
                            Cantidad = 10,
                            CartaFId = 60,
                            CartaFName = "Zur el Encantador",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/c98ae71d8806dd919d3957532efa5083/items/1/XCMR/510720.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 76,
                            Cantidad = 20,
                            CartaFId = 61,
                            CartaFName = "Devolver el favor",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/1fedf8ffa935b0c57e9e72b98d244421/items/1/ROE/22567.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 77,
                            Cantidad = 30,
                            CartaFId = 62,
                            CartaFName = "Protectora de esencia",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/62d92924aaef812ff996b5d3e725841c/items/1/PLC/14324.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 78,
                            Cantidad = 40,
                            CartaFId = 63,
                            CartaFName = "Black Lotus",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/82721fdcc32d450e26c2e52900e58f17/items/1/LEA/5465.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 79,
                            Cantidad = 10,
                            CartaFId = 64,
                            CartaFName = "King Vegeta, Umbral Invader",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/da48a0b1a709e19aabfe340c207f51df/items/1049/BT13/557521.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 80,
                            Cantidad = 20,
                            CartaFId = 65,
                            CartaFName = "Royal Supremacy",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/d90bd04a2e5f72717e8c7bd86ffae51b/items/1049/BT13/557546.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 81,
                            Cantidad = 30,
                            CartaFId = 66,
                            CartaFName = "Golden Frieza, Pinnacle of the Clan",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/550021.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 82,
                            Cantidad = 40,
                            CartaFId = 83,
                            CartaFName = "SS4 Vegeta, Thwarting the Dark Empire",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/01ffd411b94cbdef5aab781cdc7d35b3/items/1049/BT13/557579.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 1
                        },
                        new
                        {
                            CartaVendedorId = 83,
                            Cantidad = 10,
                            CartaFId = 67,
                            CartaFName = "Frieza, Revived and Reviled",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/a64b38b5ad3f59b8f1b2c55b2116eab4/items/1049/BT13/557533.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 84,
                            Cantidad = 20,
                            CartaFId = 68,
                            CartaFName = "The Power of a Super Saiyan",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/e8a55cc61ee2cc9246eb0021085db33e/items/1049/BT13/557572.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 85,
                            Cantidad = 30,
                            CartaFId = 69,
                            CartaFName = "Majin Buu, Assault of the Agents of Destruction",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549866.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 86,
                            Cantidad = 40,
                            CartaFId = 83,
                            CartaFName = "SS4 Vegeta, Thwarting the Dark Empire",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/01ffd411b94cbdef5aab781cdc7d35b3/items/1049/BT13/557579.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 2
                        },
                        new
                        {
                            CartaVendedorId = 87,
                            Cantidad = 10,
                            CartaFId = 70,
                            CartaFName = "Bardock, Pride of a Low-Class Warrior",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549721.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 88,
                            Cantidad = 20,
                            CartaFId = 71,
                            CartaFName = "Demon God Towa, Ritual at Hand",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/1591f47c3f3b0a081912dd7a90e470d4/items/1049/BT13/557586.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 89,
                            Cantidad = 30,
                            CartaFId = 72,
                            CartaFName = "Chilled, Let the Battle Begin",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/602cb1dd0d7d3ea4b08fb1f75d61b7e3/items/1049/BT13/557522.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 90,
                            Cantidad = 40,
                            CartaFId = 83,
                            CartaFName = "SS4 Vegeta, Thwarting the Dark Empire",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/01ffd411b94cbdef5aab781cdc7d35b3/items/1049/BT13/557579.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 3
                        },
                        new
                        {
                            CartaVendedorId = 91,
                            Cantidad = 10,
                            CartaFId = 73,
                            CartaFName = "SS Bardock, Super Saiyan Enlightenment",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549746.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 92,
                            Cantidad = 20,
                            CartaFId = 74,
                            CartaFName = "SS2 Son Gohan, Astonishing Strike",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549876.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 93,
                            Cantidad = 30,
                            CartaFId = 75,
                            CartaFName = "SSB Vegeta, at Full Power",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549801.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 94,
                            Cantidad = 40,
                            CartaFId = 83,
                            CartaFName = "SS4 Vegeta, Thwarting the Dark Empire",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/01ffd411b94cbdef5aab781cdc7d35b3/items/1049/BT13/557579.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 4
                        },
                        new
                        {
                            CartaVendedorId = 95,
                            Cantidad = 10,
                            CartaFId = 76,
                            CartaFName = "SS Son Goku, the Legend Personified",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549756.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 96,
                            Cantidad = 20,
                            CartaFId = 77,
                            CartaFName = "Darkness Judgment",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/049c1544d12a5ed4efc5755a9cbfd855/items/1049/BT13/557599.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 97,
                            Cantidad = 30,
                            CartaFId = 78,
                            CartaFName = "SSB Son Goku, at Full Power",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549781.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 98,
                            Cantidad = 40,
                            CartaFId = 82,
                            CartaFName = "Majin Buu, Assault of the Agents of Destruction (V.2 - Special Rare)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/23a714196691e1097092b657e2fcf815/items/1049/BT13/565913.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 5
                        },
                        new
                        {
                            CartaVendedorId = 99,
                            Cantidad = 10,
                            CartaFId = 79,
                            CartaFName = "Mechikabura, Ritual at Hand",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/304f666ad0dba00c97635d4f7ad60a35/items/1049/BT13/557591.jpg",
                            Idioma = "es",
                            Precio = 25.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 100,
                            Cantidad = 20,
                            CartaFId = 80,
                            CartaFName = "Boujack, on a Rampage",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549926.jpg",
                            Idioma = "es",
                            Precio = 50.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 101,
                            Cantidad = 30,
                            CartaFId = 81,
                            CartaFName = "King Vegeta's Imposing Presence",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/b2489b166588dfe01f642656655e717a/items/1049/BT13/549846.jpg",
                            Idioma = "es",
                            Precio = 75.0,
                            VendedorFId = 6
                        },
                        new
                        {
                            CartaVendedorId = 102,
                            Cantidad = 40,
                            CartaFId = 82,
                            CartaFName = "Majin Buu, Assault of the Agents of Destruction (V.2 - Special Rare)",
                            Estado = "Perfecta",
                            FImg = "https://static.cardmarket.com/img/23a714196691e1097092b657e2fcf815/items/1049/BT13/565913.jpg",
                            Idioma = "es",
                            Precio = 100.0,
                            VendedorFId = 6
                        });
                });

            modelBuilder.Entity("RinconDL.Entities.Juego", b =>
                {
                    b.Property<int>("JuegoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JuegoName")
                        .HasColumnType("TEXT");

                    b.HasKey("JuegoId");

                    b.ToTable("Juegos");

                    b.HasData(
                        new
                        {
                            JuegoId = 1,
                            JuegoName = "Pokemon"
                        },
                        new
                        {
                            JuegoId = 2,
                            JuegoName = "Yu-Gi-Oh"
                        },
                        new
                        {
                            JuegoId = 3,
                            JuegoName = "Magic"
                        },
                        new
                        {
                            JuegoId = 4,
                            JuegoName = "Dragon Ball"
                        });
                });

            modelBuilder.Entity("RinconDL.Entities.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartFId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("PedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RinconDL.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Seller")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Email = "pipo@gmail.com",
                            Password = "Pipo",
                            Seller = true,
                            UserName = "Pipo"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Email = "papo@gmail.com",
                            Password = "Papo",
                            Seller = true,
                            UserName = "Papo"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Email = "adri@gmail.com",
                            Password = "pipo",
                            Seller = true,
                            UserName = "Adri"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Email = "sandra@gmail.com",
                            Password = "pipo",
                            Seller = true,
                            UserName = "Sandra"
                        },
                        new
                        {
                            UsuarioId = 5,
                            Email = "jere@gmail.com",
                            Password = "pipo",
                            Seller = true,
                            UserName = "Jere"
                        },
                        new
                        {
                            UsuarioId = 6,
                            Email = "diego@gmail.com",
                            Password = "pipo",
                            Seller = true,
                            UserName = "Diego"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
